start1/_overview/startsite1_liauchuk/startsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^start/', include('start.urls', namespace="start")),
    url(r'^paranoia.admin/', include(admin.site.urls)),
)

start1/_overview/startsite3_liauchuk/registration/backends/simple/urls.py
"""
URLconf for registration and activation, using django-registration's
one-step backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.simple.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.views.generic.base import TemplateView

from registration.backends.simple.views import RegistrationView


urlpatterns = patterns('',
                       url(r'^register/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
                       )

start1/_overview/startsite3_liauchuk/startsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='start/')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    (r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/')),
    url(r'^users/', RedirectView.as_view(url='/')),
    url(r'^start/', include('start.urls', namespace="start")),
    url(r'^paranoia.admin/', include(admin.site.urls)),
)

start1/polls/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

from polls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', RedirectView.as_view(url='polls/list/today')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/polls/accounts/login'}),
    (r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/')),
    url(r'^accounts/users/', RedirectView.as_view(url='/polls/accounts/login')),

    url(r'^$', views.login, name='login'),
    url(r'^list/(?P<type>\w+)$', views.list, name='list'),
    url(r'^add-task/$', views.addtask, name='addtask'),
    url(r'^remove$', views.remove, name='remove'),
    url(r'^fix$', views.fix, name='fix'),
)

start1/start1/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()
from polls import views


urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='/polls/list/today')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/polls/accounts/login'}),
    (r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^paranoia.admin/', include(admin.site.urls)),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/polls/list/today')),
    url(r'^users/', RedirectView.as_view(url='/polls/list/today')),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^paranoia.admin/', include(admin.site.urls)),
)

start1/polls/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
  title = models.CharField(max_length=200)
  is_fixed = models.BooleanField(default=False)
  date = models.DateTimeField('date to fix')
  user = models.ForeignKey(User)

  def __unicode__(self):
    return self.title

start1/polls/forms.py
from django import forms
from polls.models import Task


class TaskForm(forms.ModelForm):
  type = forms.CharField(widget=forms.HiddenInput())
  date = forms.DateField(widget=forms.DateInput(format = '%d.%m.%Y'), input_formats=('%d.%m.%Y',))
  class Meta:
    model = Task
    labels = {
            'title': 'Title',
            'date': 'Date',
        }
    help_texts = {
            'title': '',
            'date': ''
        }
    widgets = { }
    exclude = ['is_fixed', 'user']

start1/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.shortcuts import render
from django.utils import timezone
import json
from django.contrib.auth.decorators import login_required

from polls.forms import TaskForm
from polls.models import Task


def login(request):
  return render(request, 'polls/login.html', {})

def index(request):
    context = {}
    return render(request, 'polls/list.html', context)


@login_required
@require_http_methods(["GET"])
def list(request, type):
    now = timezone.now()
    tasks = []
    if type == 'today':
      tasks = Task.objects.filter(date__lte=now,is_fixed=False,user_id=request.user.id)
    if type == 'someday':
      tasks = Task.objects.filter(date__gt=now,is_fixed=False,user_id=request.user.id)
    if type == 'fixed':
      tasks = Task.objects.filter(is_fixed=True,user_id=request.user.id)

    tasks.order_by('-date')
    context = {'tasks_list': tasks, 'type': type }
    return render(request, 'polls/list.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def addtask(request):

  if request.method == 'POST':
    try:
      form = TaskForm(request.POST)
      if not form.is_valid():
        return render(request, 'polls/addtask.html', {'form':form, 'message':'Form is invalid'})
      f = form.save(commit=False)
      f.user = request.user
      f.save()
      type = form.cleaned_data['type']
    except ValueError as e:
      return render(request, 'polls/addtask.html', {'message':e})

    return HttpResponseRedirect('/polls/list/{0}'.format(type))
  else:
    type = request.GET.get('type')
    if not type:
      type = 'today'
    form = TaskForm(initial={'type': type})
    return render(request, 'polls/addtask.html', {'form': form, 'type': type})

@login_required
@require_http_methods(["POST"])
def remove(request):
    ids = request.POST.getlist('ids')
    map(lambda id: Task.objects.filter(id=id).delete(), ids)
    return HttpResponse(json.dumps({'is_success':True, 'ids': ids}), content_type="application/json")


@login_required
@require_http_methods(["POST"])
def fix(request):
    ids = request.POST.getlist('ids')
    map(lambda id: Task.objects.filter(id=id).update(is_fixed=True), ids)
    return HttpResponse(json.dumps({'is_success':True, 'ids': ids}), content_type="application/json")

start1/polls/templates/polls/addtask.html
{% extends "polls/base.html" %}

{% block title %}Add new task{% endblock %}

{% block content %}

<div class="well">
{% if message %}
  <div class="alert alert-danger">{{message}}</div>
{% endif %}
<form class="form-horizontal" role="form" action="/polls/add-task/" method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <button type="submit" class="btn btn-default">Add task</button>
    </div>
  </div>
</form>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    var options = {format:'dd.mm.yyyy'};
    $('[name="date"]').datepicker(options);
  });
</script>
{% endblock %}




<!--
  <div class="form-group">
    <label for="Title" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="title" id="Title" placeholder="Title" value="{{title}}">
    </div>
  </div>
  <div class="form-group">
    <label for="Date" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-4">
      <input class="form-control" name="date" id="Date" type="text" data-date-format="dd-mm-yyyy">
    </div>
  </div>
-->

start1/polls/templates/polls/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/dist/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/datepicker/css/datepicker.css' %}">

    <script src="{% static 'polls/jquery-1.11.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'polls/dist/js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'polls/datepicker/js/bootstrap-datepicker.js' %}" type="text/javascript"></script>
    <title>{% block title %}Python winter school{% endblock %}</title>
</head>


<body>
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div class="navbar-collapse collapse">
            {% if user.is_authenticated %}
                <div class="navbar-header navbar-right">
                    <a class="navbar-brand" href="{% url 'polls:auth_logout' %}">Logout</a>
                </div>
                <div class="navbar-header navbar-right">
                    <a class="navbar-brand" href="#">Hello, {{ user.username }}</a>
                </div>
        {% else %}

            <div class="form-group">
                <div class="navbar-header navbar-right">
                    <a class="navbar-brand" href="{% url 'polls:auth_login' %}">Login</a>
                </div>
                <div class="navbar-header navbar-right">
                    <a class="navbar-brand" href="{% url 'polls:registration_register' %}">Register</a>
                </div>
            </div>

        {% endif %}
    </div>
    </div>
</div>

    <div class="container" id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

start1/polls/templates/polls/detail.html
<h1>{{ poll.title }}</h1>
<ul>
    <li>{{ poll.date }}</li>
</ul>

start1/polls/templates/polls/list.html
{% extends "polls/base.html" %}
{% load staticfiles %}

{% block content %}

{% csrf_token %}

<div class="well">
  <a class="btn btn-primary btn-xs {% if type == 'today' %}active{% endif %}" role="button" href="{% url 'polls:list' 'today' %} ">Today</a>
  <a class="btn btn-primary btn-xs {% if type == 'someday' %}active{% endif %}" role="button" href="{% url 'polls:list' 'someday' %}">Someday</a>
  <a class="btn btn-primary btn-xs {% if type == 'fixed' %}active{% endif %}" role="button" href="{% url 'polls:list' 'fixed' %}">Fixed</a>
</div>
{% if tasks_list %}

  <table class="table">
    <thead>
      <tr>
          <th class="col-sm-0"></th>
          <th>Title</th>
          <th>Date</th>
      </tr>
    </thead>
    <tbody>
    {% for task in tasks_list %}
    <tr>
        <td class="col-sm-1" style="text-align: center; vertical-align: middle;">
              <input class="span4" type="checkbox" data-id="{{task.id}}">
        </td>
        <td>{{ task.title }}</td>
        <td>{{ task.date|date:"d.m.Y" }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
    {% if type != 'fixed' %}
        <a class="btn btn-primary btn-xs" role="button" href="{% url 'polls:addtask' %}?type={{type}}">Add task</a>
        <a class="btn btn-info btn-xs btn-fix" role="button" href="javascript:void(0)">Fix</a>
    {% endif %}
    <a class="btn btn-info btn-xs btn-remove" role="button" href="javascript:void(0)">Remove</a>

  {% else %}

    <p>No tasks are available.</p>

    {% if type != 'fixed' %}
        <a class="btn btn-primary btn-xs" role="button" href="{% url 'polls:addtask' %}?type={{type}}">Add task</a>
    {% endif %}

  {% endif %}


<script src="{% static 'polls/utils.js' %}" type="text/javascript"></script>
<script src="{% static 'polls/modellist.js' %}" type="text/javascript"></script>

<script type="text/javascript">
  $(document).ready(function(){
      var settings = {
      };
      var model = new List(settings);
      model.initPage();
    });
</script>

{% endblock %}

start1/polls/templates/polls/login.html
{% extends "polls/base.html" %}
{% load staticfiles %}

{% block content %}
{% csrf_token %}

<!-- Button trigger modal -->

<div class="container">
    <hr class="prettyline">
    <br>
    <center>
    <h1><b>Sorry</b></h1>
    <h3>You need to sign in or register for this service</h3>
    <br>
  <button class="btn btn-primary btn-lg" href="#signup" data-toggle="modal" data-target=".bs-modal-sm">Sign In/Register</button>
  </center>
  <br>
    <hr class="prettyline">
 </div>


<!-- Modal -->
<div class="modal fade bs-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <br>
        <div class="bs-example bs-example-tabs">
            <ul id="myTab" class="nav nav-tabs">
              <li class="active"><a href="#signin" data-toggle="tab">Sign In</a></li>
              <li class=""><a href="#signup" data-toggle="tab">Register</a></li>
            </ul>
        </div>
      <div class="modal-body">
        <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="signin">
            <form class="form-horizontal">
            <fieldset>
            <!-- Sign In Form -->
            <!-- Text input-->
            <div class="control-group">
              <label class="control-label" for="userid">Alias:</label>
              <div class="controls">
                <input required="" id="userid" name="userid" type="text" class="form-control" placeholder="JoeSixpack" class="input-medium" required="">
              </div>
            </div>

            <!-- Password input-->
            <div class="control-group">
              <label class="control-label" for="passwordinput">Password:</label>
              <div class="controls">
                <input required="" id="passwordinput" name="passwordinput" class="form-control" type="password" placeholder="********" class="input-medium">
              </div>
            </div>

            <!-- Multiple Checkboxes (inline) -->
            <div class="control-group">
              <label class="control-label" for="rememberme"></label>
              <div class="controls">
                <label class="checkbox inline" for="rememberme-0">
                  <input type="checkbox" name="rememberme" id="rememberme-0" value="Remember me">
                  Remember me
                </label>
              </div>
            </div>

            <!-- Button -->
            <div class="control-group">
              <label class="control-label" for="signin"></label>
              <div class="controls">
                <button id="signin" name="signin" class="btn btn-success">Sign In</button>
              </div>
            </div>
            </fieldset>
            </form>
        </div>
        <div class="tab-pane fade" id="signup">
            <form class="form-horizontal">
            <fieldset>
            <!-- Sign Up Form -->
            <!-- Text input-->
            <div class="control-group">
              <label class="control-label" for="Email">Email:</label>
              <div class="controls">
                <input id="Email" name="Email" class="form-control" type="text" placeholder="JoeSixpack@sixpacksrus.com" class="input-large" required="">
              </div>
            </div>

            <!-- Text input-->
            <div class="control-group">
              <label class="control-label" for="userid">Alias:</label>
              <div class="controls">
                <input id="userid" name="userid" class="form-control" type="text" placeholder="JoeSixpack" class="input-large" required="">
              </div>
            </div>

            <!-- Password input-->
            <div class="control-group">
              <label class="control-label" for="password">Password:</label>
              <div class="controls">
                <input id="password" name="password" class="form-control" type="password" placeholder="********" class="input-large" required="">
              </div>
            </div>

            <!-- Button -->
            <div class="control-group">
              <label class="control-label" for="confirmsignup"></label>
              <div class="controls">
                <button id="confirmsignup" name="confirmsignup" class="btn btn-success">Sign Up</button>
              </div>
            </div>
            </fieldset>
            </form>
      </div>
    </div>
      </div>
      <div class="modal-footer">
      <center>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </center>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
</script>

{% endblock %}